name: oOf dynamic again

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: http://otafsg1.h2os.com/patch/amazone2/GLO/OnePlus7Oxygen/OnePlus7Oxygen_13.W.41_GLO_041_2007291632/OnePlus7Oxygen_13.W.41_OTA_041_all_2007291632_938c0a4f529d725.zip
  ROM_NAME: OP7-Beta
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Initializing environments
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
            sudo apt-get update -y
            sudo apt-get install -y simg2img 
            sudo apt-get install zip gzip tar
            sudo -E apt-get install expect
            sudo pip3 install --upgrade setuptools
            sudo pip3 install --upgrade pip
            sudo apt update 2>/dev/null | grep packages
        
       - name: Initializing Payload
         run: |
              sudo aria2c http://tdrive.manofuranium.workers.dev/payload_dumper_tool_by_ius.zip
              sudo unzip *.zip
              cd payload_dumper
              sudo python3 -m pip install protobuf
              
       - name: Downloading FW
         run: |
              cd payload_dumper
              sudo aria2c $ROM_URL
              
       - name: Extracting Payload
         run: |
              cd payload_dumper    
              sudo unzip *.zip
              sudo python3 payload_dumper.py payload.bin
              ls
              
       - name: Copying final zipp
         run: |
              mkdir lol
              sudo cp -r payload_dumper/system.img lol
              sudo cp -r payload_dumper/product.img lol
              sudo cp -r payload_dumper/opproduct.img lol 
              sudo cp -r payload_dumper/vendor.img lol
              
       - name: Extracting Sytem Overlay
         run: |
              cd lol
              sudo mkdir lel
              sudo mount -ro loop product.img lel/
              sudo zip -r $ROM_NAME-SystemOverlay.zip lel/overlay
              curl -sL https://git.io/file-transfer | sh
              ./transfer gof $ROM_NAME-SystemOverlay.zip
              
       - name: Extracting Vendor Overlay
         run: |
              cd lol
              sudo mkdir lel1
              sudo mount -ro loop vendor.img lel1/
              sudo zip -r $ROM_NAME-VendorOverlay.zip lel1/overlay
              ./transfer gof $ROM_NAME-VendorOverlay.zip
              
       - name: Extracting OnePlus Folder
         run: |
              cd lol
              sudo mkdir lel2
              sudo mount -ro loop opproduct.img lel2/
              sudo zip -r $ROM_NAME-OneplusFolder.zip lel2/build.prop lel2/feature_list
              ./transfer gof $ROM_NAME-OneplusFolder.zip
      
       - name: Initializing telegram bot
         env:
              TOKEN: ${{ secrets.TOKEN }}

         run: |
              sudo install telegram /usr/bin
              chmod +x initial.sh
              ./initial.sh
              
       - name: Execute Shell Script
         env:
              TOKEN: ${{ secrets.TOKEN }}

         run: |
               chmod +x upload.sh
               ./upload.sh
