name: Running bot
 
on: push

env:
  TZ: America/Recife

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 525600

    steps:
       - name: Checkouts
         uses: actions/checkout@master
         
       - name: Initializing environments
         continue-on-error: true
         timeout-minutes: 100
         run: |
              git config --global user.name "Kurata-Yui"
              git config --global user.email "secrets.EMAILGIT"
              mkdir tmp && cd tmp
              git clone https://github.com/Kurata-Yui/Kurata-Yui Kurata-Yui

       - name: Setup Erfan
         continue-on-error: true
         timeout-minutes: 10
         run: |
              git clone --recurse-submodules https://github.com/Treble-Experience/ErfanGSIs-VelanGSIs ErfanGSIs
              cd Erf*; sudo bash setup.sh

       - name: Setup BoboBot
         continue-on-error: true
         timeout-minutes: 10
         run: |
              git clone https://${{ secrets.USERNAME }}":${{ secrets.GITTOKEN }}"@github.com/Kurata-Yui/Bot3-Jar Bobo
              mv Bobo/*.jar .; rm -rf Bobo

       - name: Run Bot3 in first time
         continue-on-error: true
         timeout-minutes: 3
         run: |
               java -jar BoboBot.jar
         
       - name: Add values
         continue-on-error: true
         timeout-minutes: 1
         run: |
              rm -rf configs/config.prop
              cd configs
              touch config.prop
              echo "bot-token=${{ secrets.TOKEN }}" >> "config.prop"
              echo "bot-username=chikatto" >> "config.prop"
              echo "bot-master=946757865" >> "config.prop"
              echo "bot-submaster=918317361" >> "config.prop"
              echo "bot-sf-pass=${{ secrets.PASSWORD }}" >> sf-creds.config
              echo "bot-sf-proj=trebleexperience" >> sf-creds.config
              echo "bot-sf-user=pything" >> sf-creds.config
              echo "bot-announcement-id=-1001179583442" >> sf-creds.config
              echo "bot-sf-host=frs.sourceforge.net" >> sf-creds.config
              echo "bot-send-announcement=true" >> sf-creds.config
             
       - name: Run Bot3
         continue-on-error: true
         timeout-minutes: 350
         run: sudo java -jar BoboBot.jar
         
       - name: Loop workflow
         continue-on-error: true
         timeout-minutes: 1
         run: |
              cd tmp/Kurata-Yui
              date=`date +%Y%m%d%h%m`
              echo "1" >> push.txt
              git add .
              git commit -m "$date: Loop workflow"
              
       - name: Reruns
         continue-on-error: true
         timeout-minutes: 5
         run: |
              cd tmp/Kurata-Yui
              sudo apt-get install expect -y
              expect -c "
              spawn git push -f 
              expect \"Username\"
              send \"yukosky\r\"
              expect \"Password\"
              send \"${{ secrets.PASSWORD }}\r\"
              expect \"master -> master\"
              set timeout -10
              interact"
